import pyvisa, time
from hmp4040Class import HMP4040
rm = pyvisa.ResourceManager()
print(rm.list_resources())
hmp = HMP4040('ASRL7::INSTR')
hmp.disable_output()
print('vav', hmp.get_voltage(1))
#print(hmp.get_voltage(2))
hmp.set_current_limit(1, 1)
print(hmp.get_current_limit(1))
start = time.time()
print(hmp.set_current_limit(1, 0.002))
print('AAAAA', type(hmp.instr.query('*OPC?')))
print(hmp.get_current_limit(1))
end = time.time()
print('time', end-start)
hmp.instr.write('INST OUT1')

print(hmp.instr.write('CURR? MIN'))
print(hmp.instr.write('CURR? MAX'))
hmp.disable_output()

#print(hmp.instr.query('CURR?'))
#print(hmp.get_current_limit(1))
#hmp.set_voltage(1, 1)
#hmp.set_voltage(1, 1)
#hmp.set_voltage(2, 0)
#hmp.set_voltage(3, 0)
#hmp.set_voltage(4, 0)
#hmp.set_current_limit(1, 1)
#hmp.set_current_limit(2, 1)
#hmp.set_current_limit(3, 1)
#hmp.set_current_limit(4, 1)
#hmp.sweep_multi_channel(1, 16, 5, 3, 3, True)